/* Checksum.ai autogenerated test */
import type { IChecksumPage } from "@checksum-ai/runtime";
import { init } from "@checksum-ai/runtime";
import { test as base } from "@playwright/test";

const { test, defineChecksumTest, login } = init(base);

test.describe("Example test", () => {
  test.beforeEach(async ({ page }: { page: IChecksumPage }) => {
    await login(page);
  });

  test(defineChecksumTest("Navigate to home page", "GPzdp"), async ({ page }) => {
    await page.goto("/");
  });
});
