/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { randomString } from "@calcom/lib/random";

import { test, defineChecksumTest, checksumAI, expect } from "../../fixtures";

test(defineChecksumTest("Book on column layout", "LAYOUT_COLUMN_001"), async ({ page, users }) => {
  let user: any;

  await checksumAI("Create a user for testing column layout booking", async () => {
    user = await users.create();
  });

  await checksumAI("Navigate to the user's booking page", async () => {
    await page.goto(`/${user.username}`);
  });

  await checksumAI("Click on the first event type to start booking", async () => {
    await page.click('[data-testid="event-type-link"]');
  });

  await checksumAI("Switch to column view layout", async () => {
    await page.click('[data-testid="toggle-group-item-column_view"]');
  });

  await checksumAI("Navigate to next month to find available time slots", async () => {
    await page.click('[data-testid="incrementMonth"]');
  });

  await checksumAI("Select the first available time slot in column view", async () => {
    await page.locator('[data-testid="time"]').nth(0).click();
  });

  await checksumAI("Fill in the attendee name", async () => {
    await page.locator('[name="name"]').fill("Test name");
  });

  await checksumAI("Fill in the attendee email address", async () => {
    await page.locator('[name="email"]').fill(`${randomString(4)}@example.com`);
  });

  await checksumAI("Add notes for the meeting", async () => {
    await page.locator('[name="notes"]').fill("Test notes");
  });

  await checksumAI("Confirm the booking by clicking the confirm button", async () => {
    await page.click('[data-testid="confirm-book-button"]');
  });

  await expect(
    page.locator("[data-testid=success-page]"),
    "The booking success page should be visible after confirming the booking in column layout"
  ).toBeVisible();
});
