/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { checksumAI, defineChecksumTest, expect, test } from "../../fixtures";

test(
  defineChecksumTest("Pro user can book an event first day in next month", "PRO_BOOK_001"),
  {},
  async ({ page, users }) => {
    await checksumAI("Create pro user and navigate to their page", async () => {
      const pro = await users.create();
      await page.goto(`/${pro.username}`);
    });
    await checksumAI("Click on the first event type to start booking", async () => {
      await page.click('[data-testid="event-type-link"]');
    });
    await checksumAI("Navigate to next month to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });
    await checksumAI("Select the first available day in the calendar", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });
    await checksumAI("Select the first available time slot", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });
    await checksumAI("Fill in the attendee name", async () => {
      await page.fill('[name="name"]', "Test User");
    });
    await checksumAI("Fill in the attendee email address", async () => {
      await page.fill('[name="email"]', "test@example.com");
    });
    await checksumAI("Add notes for the meeting", async () => {
      await page.fill('[name="notes"]', "Test notes");
    });
    await checksumAI("Confirm the booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-button"]');
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the booking"
    ).toBeVisible();
  }
);
