/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { test, defineChecksumTest, checksumAI, expect } from "../../fixtures";

test.skip(
  defineChecksumTest("Can book an unconfirmed event multiple times", "PRO_UNCONFIRMED_MULTIPLE_001"),
  {
    annotation: {
      type: "IntentionallyBroken",
      description:
        'Changed locator from \'[data-testid="event-type-link"]:has-text("Opt in")\' to \'[data-testid="event-type-link-broken"]:has-text("Opt in")\' to simulate a component refactor where the selector was updated.',
    },
  },
  async ({ page, users, variableStore }) => {
    await checksumAI("Create a pro user for testing unconfirmed event booking", async () => {
      variableStore.pro = await users.create();
    });

    await checksumAI("Navigate to the pro user's booking page", async () => {
      await page.goto(`/${variableStore.pro.username}`);
    });

    await checksumAI("Click on the opt-in event type that requires confirmation", async () => {
      await page.locator('[data-testid="event-type-link-broken"]:has-text("Opt in")').click();
    });

    await checksumAI("Navigate to next month to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });

    await checksumAI("Select the first available day in the calendar", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });

    await checksumAI("Select the first available time slot", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });

    await checksumAI("Fill in the attendee name", async () => {
      await page.fill('[name="name"]', "Test User");
    });

    await checksumAI("Fill in the attendee email address", async () => {
      await page.fill('[name="email"]', "test@example.com");
    });

    await checksumAI("Add notes for the meeting", async () => {
      await page.fill('[name="notes"]', "Test notes");
    });

    await checksumAI("Confirm the booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-book-button"]');
    });

    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the first booking"
    ).toBeVisible();

    await checksumAI("Save the booking page URL for the second booking", async () => {
      variableStore.pageUrl = page.url();
    });

    await checksumAI("Navigate back to the booking page to re-book", async () => {
      await page.goto(variableStore.pageUrl);
    });

    await checksumAI("Navigate to next month again to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });

    await checksumAI("Select the first available day in the calendar again", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });

    await checksumAI("Select the first available time slot again", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });

    await checksumAI("Fill in the attendee name for the second booking", async () => {
      await page.fill('[name="name"]', "Test User 2");
    });

    await checksumAI("Fill in the attendee email address for the second booking", async () => {
      await page.fill('[name="email"]', "test2@example.com");
    });

    await checksumAI("Add notes for the second meeting", async () => {
      await page.fill('[name="notes"]', "Test notes 2");
    });

    await checksumAI("Confirm the second booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-book-button"]');
    });

    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the second booking"
    ).toBeVisible();
  }
);
