/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { WEBAPP_URL } from "@calcom/lib/constants";

import { test, defineChecksumTest, checksumAI, expect } from "../../fixtures";

test.skip(
  defineChecksumTest("Returns 404 when requested event type does not exist", "PRO_404_001"),
  async ({ page, users, variableStore }) => {
    await checksumAI("Create a pro user for testing 404 functionality", async () => {
      variableStore.pro = await users.create();
    });

    await checksumAI("Navigate to non-existent event type", async () => {
      const unexistingPageUrl = new URL(`${variableStore.pro.username}/invalid-event-type`, WEBAPP_URL);
      variableStore.response = await page.goto(unexistingPageUrl.href);
    });

    await expect(
      variableStore.response,
      "The response should return a 404 status when accessing a non-existent event type"
    ).toHaveProperty("status", 404);
  }
);
