/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { checksumAI, defineChecksumTest, expect, test } from "../../fixtures";

test(
  defineChecksumTest("Redirect with special characters in username should not throw 500", "SPECIAL_CHAR_003"),
  async ({ page, users, variableStore }) => {
    await checksumAI("Create a user with special characters and single event type", async () => {
      variableStore.benny = await users.create({
        username: "ßenny", // ß is a special character
        eventTypes: [
          {
            title: "15 min",
            slug: "15-min",
            length: 15,
          },
        ],
        overrideDefaultEventTypes: true,
      });
    });

    await checksumAI("Navigate to user page", async () => {
      // This redirects to /[user]/[type] because this user has only 1 event-type
      variableStore.response = await page.goto(`/${variableStore.benny.username}`);
    });

    await expect(variableStore.response?.status(), "Redirect should work without 500 error").not.toBe(500);
  }
);
