/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { test, defineChecksumTest, checksumAI, expect } from "../../fixtures";

test(
  defineChecksumTest("Redirect with special characters in username should not throw 500", "SPECIAL_CHAR_003"),
  async ({ page, users }) => {
    await checksumAI("Create a user with special characters and single event type", async () => {
      const benny = await users.create({
        username: "ßenny", // ß is a special character
        eventTypes: [
          {
            title: "15 min",
            slug: "15-min",
            length: 15,
          },
        ],
        overrideDefaultEventTypes: true,
      });
    });

    await checksumAI("Navigate to user page and verify redirect works without 500 error", async () => {
      const benny = await users.create({
        username: "ßenny", // ß is a special character
        eventTypes: [
          {
            title: "15 min",
            slug: "15-min",
            length: 15,
          },
        ],
        overrideDefaultEventTypes: true,
      });
      // This redirects to /[user]/[type] because this user has only 1 event-type
      const response = await page.goto(`/${benny.username}`);
      expect(response?.status()).not.toBe(500);
    });
  }
);
