/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { randomString } from "@calcom/lib/random";

import { checksumAI, defineChecksumTest, expect, test } from "../../fixtures";

test(
  defineChecksumTest("Reschedule and cancel buttons should be hidden on success page", "DISABLED_CANCEL_001"),
  {},
  async ({ page, users }) => {
    let user: any;
    let bookingId: string;
    await checksumAI("Create a user with disabled cancellation and rescheduling event type", async () => {
      user = await users.create({
        name: `Test-user-${randomString(4)}`,
        eventTypes: [
          {
            title: "No Cancel No Reschedule",
            slug: "no-cancel-no-reschedule",
            length: 30,
            disableCancelling: true,
            disableRescheduling: true,
          },
        ],
      });
    });
    await checksumAI("Navigate to the event type booking page", async () => {
      await page.goto(`/${user.username}/no-cancel-no-reschedule`);
    });
    await checksumAI("Navigate to next month to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });
    await checksumAI("Select the first available day in the calendar", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });
    await checksumAI("Select the first available time slot", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });
    await checksumAI("Fill in the attendee name", async () => {
      await page.fill('[name="name"]', "Test-user-1");
    });
    await checksumAI("Fill in the attendee email address", async () => {
      await page.fill('[name="email"]', "test-booker@example.com");
    });
    await checksumAI("Add notes for the meeting", async () => {
      await page.fill('[name="notes"]', "Test notes");
    });
    await checksumAI("Confirm the booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-book-button"]');
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the booking"
    ).toBeVisible();
    await checksumAI("Extract the booking ID from the URL", async () => {
      const url = new URL(page.url());
      const pathSegments = url.pathname.split("/");
      bookingId = pathSegments[pathSegments.length - 1];
    });
    await expect(
      page.locator('[data-testid="reschedule-button"]'),
      "The reschedule link should be hidden for events with disabled rescheduling"
    ).toBeHidden();
    await expect(
      page.locator('[data-testid="cancel"]'),
      "The cancel button should be hidden for events with disabled cancellation"
    ).toBeHidden();
  }
);
test(
  defineChecksumTest(
    "Direct access to reschedule/{bookingId} should redirect to success page",
    "DISABLED_CANCEL_002"
  ),
  async ({ page, users }) => {
    let user: any;
    let bookingId: string;
    await checksumAI("Create a user with disabled cancellation and rescheduling event type", async () => {
      user = await users.create({
        name: `Test-user-${randomString(4)}`,
        eventTypes: [
          {
            title: "No Cancel No Reschedule",
            slug: "no-cancel-no-reschedule",
            length: 30,
            disableCancelling: true,
            disableRescheduling: true,
          },
        ],
      });
    });
    await checksumAI("Navigate to the event type booking page", async () => {
      await page.goto(`/${user.username}/no-cancel-no-reschedule`);
    });
    await checksumAI("Navigate to next month to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });
    await checksumAI("Select the first available day in the calendar", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });
    await checksumAI("Select the first available time slot", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });
    await checksumAI("Fill in the attendee name", async () => {
      await page.fill('[name="name"]', "Test-user-1");
    });
    await checksumAI("Fill in the attendee email address", async () => {
      await page.fill('[name="email"]', "test-booker@example.com");
    });
    await checksumAI("Add notes for the meeting", async () => {
      await page.fill('[name="notes"]', "Test notes");
    });
    await checksumAI("Confirm the booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-book-button"]');
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the booking"
    ).toBeVisible();
    await checksumAI("Extract the booking ID from the URL", async () => {
      const url = new URL(page.url());
      const pathSegments = url.pathname.split("/");
      bookingId = pathSegments[pathSegments.length - 1];
    });
    await checksumAI("Navigate directly to the reschedule page for the booking", async () => {
      await page.goto(`/reschedule/${bookingId}`);
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The success page should be visible when accessing reschedule page directly"
    ).toBeVisible();
    await expect(
      page,
      "The page should redirect to the booking page when accessing reschedule directly"
    ).toHaveURL((url) => url.pathname === `/booking/${bookingId}`);
  }
);
test(
  defineChecksumTest(
    "Using rescheduleUid query parameter should redirect to success page",
    "DISABLED_CANCEL_003"
  ),
  async ({ page, users }) => {
    let user: any;
    let bookingId: string;
    await checksumAI("Create a user with disabled cancellation and rescheduling event type", async () => {
      user = await users.create({
        name: `Test-user-${randomString(4)}`,
        eventTypes: [
          {
            title: "No Cancel No Reschedule",
            slug: "no-cancel-no-reschedule",
            length: 30,
            disableCancelling: true,
            disableRescheduling: true,
          },
        ],
      });
    });
    await checksumAI("Navigate to the event type booking page", async () => {
      await page.goto(`/${user.username}/no-cancel-no-reschedule`);
    });
    await checksumAI("Navigate to next month to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });
    await checksumAI("Select the first available day in the calendar", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });
    await checksumAI("Select the first available time slot", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });
    await checksumAI("Fill in the attendee name", async () => {
      await page.fill('[name="name"]', "Test-user-1");
    });
    await checksumAI("Fill in the attendee email address", async () => {
      await page.fill('[name="email"]', "test-booker@example.com");
    });
    await checksumAI("Add notes for the meeting", async () => {
      await page.fill('[name="notes"]', "Test notes");
    });
    await checksumAI("Confirm the booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-book-button"]');
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the booking"
    ).toBeVisible();
    await checksumAI("Extract the booking ID from the URL", async () => {
      const url = new URL(page.url());
      const pathSegments = url.pathname.split("/");
      bookingId = pathSegments[pathSegments.length - 1];
    });
    await checksumAI("Navigate to the event type with rescheduleUid query parameter", async () => {
      await page.goto(`/${user.username}/no-cancel-no-reschedule?rescheduleUid=${bookingId}`);
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The success page should be visible when using rescheduleUid query parameter"
    ).toBeVisible();
    await expect(
      page,
      "The page should redirect to the booking page when using rescheduleUid query parameter"
    ).toHaveURL((url) => url.pathname === `/booking/${bookingId}`);
  }
);
test(
  defineChecksumTest("Should prevent cancellation and show an error message", "DISABLED_CANCEL_004"),
  async ({ page, users }) => {
    let user: any;
    let bookingId: string;
    await checksumAI("Create a user with disabled cancellation and rescheduling event type", async () => {
      user = await users.create({
        name: `Test-user-${randomString(4)}`,
        eventTypes: [
          {
            title: "No Cancel No Reschedule",
            slug: "no-cancel-no-reschedule",
            length: 30,
            disableCancelling: true,
            disableRescheduling: true,
          },
        ],
      });
    });
    await checksumAI("Navigate to the event type booking page", async () => {
      await page.goto(`/${user.username}/no-cancel-no-reschedule`);
    });
    await checksumAI("Navigate to next month to find available time slots", async () => {
      await page.click('[data-testid="incrementMonth"]');
    });
    await checksumAI("Select the first available day in the calendar", async () => {
      await page.locator('[data-testid="day"][data-disabled="false"]').nth(0).click();
    });
    await checksumAI("Select the first available time slot", async () => {
      await page.locator('[data-testid="time"]').nth(0).click();
    });
    await checksumAI("Fill in the attendee name", async () => {
      await page.fill('[name="name"]', "Test-user-1");
    });
    await checksumAI("Fill in the attendee email address", async () => {
      await page.fill('[name="email"]', "test-booker@example.com");
    });
    await checksumAI("Add notes for the meeting", async () => {
      await page.fill('[name="notes"]', "Test notes");
    });
    await checksumAI("Confirm the booking by clicking the confirm button", async () => {
      await page.click('[data-testid="confirm-book-button"]');
    });
    await expect(
      page.locator("[data-testid=success-page]"),
      "The booking success page should be visible after confirming the booking"
    ).toBeVisible();
    await checksumAI("Extract the booking ID from the URL", async () => {
      const url = new URL(page.url());
      const pathSegments = url.pathname.split("/");
      bookingId = pathSegments[pathSegments.length - 1];
    });
    await checksumAI("Attempt to cancel the booking via API request", async () => {
      const response = await page.request.post("/api/cancel", {
        data: {
          uid: bookingId,
        },
        headers: {
          "Content-Type": "application/json",
        },
      });
      expect(response.status()).toBe(400);
      const responseBody = await response.json();
      expect(responseBody.message).toBe("This event type does not allow cancellations");
    });
  }
);
