/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { test, defineChecksumTest, checksumAI, expect } from "../../fixtures";

test(
  defineChecksumTest("Default - No date range filter selected", "OOO_DATE_FILTER_DEFAULT_001"),
  {
    annotation: {
      type: "IntentionallyBroken",
      description: {
        change: "There's no such filter - this is unrecoverable error",
        shouldAutoRecover: false,
        shouldPass: false,
      },
    },
  },
  async ({ page, users, variableStore }) => {
    await checksumAI("Create a user", async () => {
      variableStore.user = await users.create({ name: "userOne" });
    });

    await checksumAI("Login as the created user", async () => {
      await variableStore.user.apiLogin();
    });

    await checksumAI("Navigate to the out of office settings page", async () => {
      const entriesListRespPromise = page.waitForResponse(
        (response) => response.url().includes("outOfOfficeEntriesList") && response.status() === 200
      );
      await page.goto("/settings/my-account/out-of-office");
      await page.waitForLoadState("domcontentloaded");
      await entriesListRespPromise;
    });

    await expect(
      page.locator('[data-testid="date-range-filter"]'),
      "The date range filter should show no filter selected by default"
    ).toContainText("All");
  }
);
