/* Checksum.ai autogenerated test with custom Cal.com fixtures */
import { test, defineChecksumTest, checksumAI, expect } from "../../fixtures";

test(
  defineChecksumTest("Profile page is loaded for users in Organization", "VFrFP"),
  {
    annotation: {
      type: "IntentionallyBroken",
      description: {
        change:
          "Changed assertion from toBeVisible() to toBeHidden() for the profile upload avatar to simulate a test expecting the wrong UI state.",
        shouldAutoRecover: true,
      },
    },
  },
  async ({ page, users, variableStore }) => {
    const teamMatesObj = [{ name: "teammate-1" }, { name: "teammate-2" }];
    const owner = await users.create(undefined, {
      hasTeam: true,
      isOrg: true,
      hasSubteam: true,
      teammates: teamMatesObj,
    });

    await checksumAI("Login with API", () => owner.apiLogin());

    await checksumAI("Navigate to profile settings page", () =>
      page.goto("/settings/my-account/profile", { waitUntil: "load" })
    );

    await expect(page.locator("img"), "Expect the profile upload avatar to be visible").toBeHidden();
  }
);
